const isStayPage = document.title.includes('ที่พัก');
const catalog = isStayPage ? [
  { name: 'Lanna Riverside Retreat', place: 'เชียงใหม่', type: 'บูทีครีสอร์ต', price: 2450, rating: '4.8', image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=85', details: ['อาหารเช้าสำหรับ 2 ท่าน', 'สระว่ายน้ำและวิวแม่น้ำ', 'ห่างจากเมืองเก่า 10 นาที'] },
  { name: 'Misty Mountain Villa', place: 'เชียงใหม่', type: 'วิลล่าวิวภูเขา', price: 3190, rating: '4.9', image: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=900&q=85', details: ['ห้องพักพร้อมระเบียงส่วนตัว', 'รถรับส่งสนามบิน', 'ที่จอดรถฟรี'] },
  { name: 'Andaman Shore Hotel', place: 'ภูเก็ต', type: 'โรงแรมริมชายหาด', price: 3850, rating: '4.7', image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=900&q=85', details: ['เดินถึงชายหาดใน 2 นาที', 'สระว่ายน้ำอินฟินิตี้', 'รวมอาหารเช้า'] },
  { name: 'Bangkok Garden Residence', place: 'กรุงเทพฯ', type: 'โรงแรมใจกลางเมือง', price: 1890, rating: '4.6', image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=900&q=85', details: ['ใกล้รถไฟฟ้า BTS', 'ฟิตเนส 24 ชั่วโมง', 'Wi‑Fi ฟรี'] }
] : [
  { name: 'Toyota Yaris ATIV', place: 'เชียงใหม่', type: 'รถเก๋งอีโคคาร์ · อัตโนมัติ', price: 890, rating: '4.8', image: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=900&q=85', details: ['ผู้โดยสาร 5 คน · กระเป๋า 2 ใบ', 'รับรถที่สนามบินเชียงใหม่', 'ประกันภัยพื้นฐานรวมแล้ว'] },
  { name: 'Honda HR-V', place: 'เชียงใหม่', type: 'SUV · อัตโนมัติ', price: 1450, rating: '4.9', image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=85', details: ['ผู้โดยสาร 5 คน · กระเป๋า 3 ใบ', 'กล้องถอยหลัง', 'ยกเลิกฟรีก่อนรับรถ 24 ชม.'] },
  { name: 'Toyota Fortuner', place: 'ภูเก็ต', type: 'SUV 7 ที่นั่ง · อัตโนมัติ', price: 2150, rating: '4.7', image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=900&q=85', details: ['ผู้โดยสาร 7 คน · กระเป๋า 4 ใบ', 'รับ–คืนรถสนามบินภูเก็ต', 'ประกันภัยพื้นฐานรวมแล้ว'] },
  { name: 'Honda City', place: 'กรุงเทพฯ', type: 'รถเก๋ง · อัตโนมัติ', price: 1050, rating: '4.6', image: 'https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=900&q=85', details: ['ผู้โดยสาร 5 คน · กระเป๋า 2 ใบ', 'รับรถได้ย่านสุขุมวิท', 'ไม่จำกัดระยะทาง'] }
];
const money = (amount) => new Intl.NumberFormat('th-TH').format(amount); const results = document.querySelector('#catalog-results'); const summary = document.querySelector('#catalog-summary'); let chosenCatalogItem;
function render(items, term = '') { summary.textContent = term ? `พบ ${items.length} รายการใน ${term}` : `แนะนำ ${items.length} รายการสำหรับคุณ`; results.innerHTML = items.length ? items.map((item, index) => `<article class="catalog-card"><img src="${item.image}" alt="${item.name}" /><div class="catalog-copy"><p>${item.type}</p><h2>${item.name}</h2><span>★ ${item.rating} · ${item.place}</span><strong>฿${money(item.price)} <small>/ ${isStayPage ? 'คืน' : 'วัน'}</small></strong><button type="button" data-detail="${index}">ดูรายละเอียด →</button></div></article>`).join('') : '<p class="empty-state">ไม่พบรายการในจังหวัดนี้ ลองค้นหา เชียงใหม่, ภูเก็ต หรือ กรุงเทพฯ</p>'; results.querySelectorAll('[data-detail]').forEach((button) => button.addEventListener('click', () => openDetail(items[Number(button.dataset.detail)]))); }
function openDetail(item) { chosenCatalogItem = item; document.querySelector('#detail-content').innerHTML = `<img class="detail-image" src="${item.image}" alt="${item.name}" /><p class="eyebrow">${item.place}</p><h2>${item.name}</h2><p class="detail-type">${item.type}</p><ul>${item.details.map((detail) => `<li>✦ ${detail}</li>`).join('')}</ul><div class="detail-price">฿${money(item.price)} <small>/ ${isStayPage ? 'คืน' : 'วัน'}</small><button class="primary" type="button">เลือก${isStayPage ? 'ที่พัก' : 'รถคันนี้'}</button></div>`; document.querySelector('#detail-modal').classList.remove('hidden'); }
function search(event) { event?.preventDefault(); const term = document.querySelector('#location').value.trim(); render(catalog.filter((item) => `${item.place} ${item.name}`.toLowerCase().includes(term.toLowerCase())), term); }
document.querySelector('#catalog-search').addEventListener('submit', search); document.querySelector('#location').addEventListener('input', search); document.querySelector('.detail-close').addEventListener('click', () => document.querySelector('#detail-modal').classList.add('hidden')); document.querySelector('#detail-modal').addEventListener('click', (event) => { if (event.target.id === 'detail-modal') event.currentTarget.classList.add('hidden'); }); document.addEventListener('click', (event) => { if (event.target.closest('.detail-price .primary') && chosenCatalogItem) { sessionStorage.setItem('checkout_item', JSON.stringify({ ...chosenCatalogItem, kind: isStayPage ? 'stay' : 'car' })); window.location.assign('checkout.html'); } }); render(catalog);
